version: '3.8'
services:
  web:
    
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 6000:6000
    depends_on:
      - mongo
    

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  
  mongo-data: